version: '3.7'
services:
  # loadBalancer:
  #   image: 'nginx:latest'
  #   ports:
  #     - '90:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app-auth
  #   networks:
  #     - default

  app-auth:
    build:
        args:
          user: moraski
          uid: 1000
        context: .././auth-laravel
        dockerfile: Dockerfile
    volumes:
      - .././auth-laravel:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9090:9090"
    networks:
      - default

  app-reports:
    build:
      context: .././reports-java
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    networks:
      - default

  mysql:
    image: 'mariadb:10.6'
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - default
  # redis:
  #   image: 'redis:latest'
  #   networks:
  #     - default

      
networks:
  default:
    driver: bridge